## 넘파이?

Numerical Python - 행열 연산이나 다차원 배열을 편리하게 처리  
배열(array) 단위로 백터, 행열 연상등을 파이썬의 기본 리스트에 비해 빠르고 적은양의 메모리로 연산  
브로드캐스트 지원 - 형태(차원)가 다른 행렬끼리의 계산

https://numpy.org/

In [ ]:
import numpy as np

## 사용하는 이유?

In [35]:
matrix_1 = [[1, 2],[3, 4]]
matrix_2 = [[5, 6],[7, 8]]
matrix_result = []

#행렬합 (파이썬 리스트사용)
for i in range(len(matrix_1)):
    tmp = []
    for j in range(len(matrix_2)):
        tmp.append(matrix_1[i][j]+matrix_2[i][j])
    matrix_result.append(tmp)
    
print(matrix_result)


#행렬합 (넘파이)
matrix_result = np.array(matrix_1) + np.array(matrix_2)
print(matrix_result)

[[6, 8], [10, 12]]
[[ 6  8]
 [10 12]]


In [34]:
#숫자와의 연산 (파이썬 리스트사용)

matrix_1 = [[1, 2],[3, 4]]

for i in range(len(matrix_1)):
    for j in range(len(matrix_2)):
        matrix_1[i][j] = matrix_1[i][j] + 1
        
print(matrix_1)

NameError: name 'matrix_2' is not defined

In [ ]:
#숫자와의 연산 (넘파이)

matrix_1 = [[1, 2],[3, 4]]

np.array(matrix_1) + 1

In [ ]:
matrix_1 = [['aa', 'bb'],[3.4, 1]]

np.array(matrix_1)

## 속도비교

In [ ]:
import time

size = 10000000

#list
x = list(range(size))
y = list(range(size))

start_time = time.time()
z = [x[i]+x[i] for i in range(size)]
print("리스트 걸린시간", time.time()-start_time)

#adlist (넘파이)
x = np.arange(size)
y = np.arange(size)
start_time = time.time()
z = x + y
print("넘파이 걸린시간", time.time()-start_time)

## ndarray

In [ ]:
x = np.uint(32)
print(x)
print(x.dtype)

In [ ]:
x = np.array([1, 2, 3, 4])
print(x)
print(x.dtype)

In [ ]:
x = np.float32([1, 2, 3, 4])
print(x)
print(x.dtype)

In [ ]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
print(x)
print(x.dtype)

x = np.int32(x)
print(x)
print(x.dtype)
np.issubdtype(x.dtype, np.int32)

## 다차원 ndarray

In [ ]:
x = np.array(1)
print(x.shape)
print(x.ndim)
print(x.size)

In [ ]:
x = np.array([1, 2])
print(x.shape)
print(x.ndim)
print(x.size)

In [ ]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print(x.shape)
print(x.ndim)
print(x.ndim)

## arange

In [ ]:
x = np.arange(10)
print(x)
x = np.arange(10.0)
print(x)
x = np.arange(1, 10, 2)
print(x)
x = np.arange(1, 10, 0.5)
print(x)
x = np.arange(10, 1, -0.5)
print(x)

## linspace

In [ ]:
x = np.linspace(1, 20, 5)
print(x)

In [ ]:
x = np.linspace(1, 20, 10, endpoint=False)
print(x)

## reshape

In [ ]:
x = np.arange(9).reshape(3, 3)
print(x)

In [ ]:
x = np.arange(24).reshape(2, 3, 4)
print(x)

In [ ]:
x = np.arange(16).reshape(2, 2, 2, 2)
print(x)

In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.reshape(2,3))

In [ ]:
x = np.arange(9).reshape(3, -1)
print(x)

## slicing

In [ ]:
x = np.arange(20)
print(x[1:3])

In [ ]:
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])

In [ ]:
x = np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5,1])

## indexing & boolean indexing

In [ ]:
a = np.arange(20).reshape(4, 5)
print(a)

print(a[1][1])
print(a[1,1])
print(a[[1,1],[1,2]])

In [ ]:
a = np.arange(20).reshape(4, 5)
print(a)

print(a > 3)
print(a[a > 3])
print(a[a == 1])
print(a[~(a == 1)])
print(a[(a > 3)&(a < 8)])

## random

In [ ]:
np.random.rand(5,5)

In [ ]:
np.random.randint(1, 10)

In [ ]:
np.random.randint(1, 10, size=(5))

In [ ]:
np.random.randint(1, 10, size=(5, 5))

## 특별한 형태의 배열

In [ ]:
np.ones([5,5])

In [ ]:
np.zeros([5,5])

In [ ]:
np.eye(5)

In [ ]:
x = np.random.randint(1, 10, size=(5, 5))
y = np.eye(5)
print(x)
z = np.dot(x, y)
print(z)

In [ ]:
x = np.random.randint(1, 10, size=(5, 5))
print(x)
print(x.ravel())
print(x.ravel(order='F'))

## concatenate

In [2]:
x = np.arange(1, 4)
y = np.arange(4, 7)

np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)

np.concatenate([x, y])

In [ ]:
np.concatenate([x, y], axis=1)

## split

In [ ]:
x = np.arange(12)
print(x)
np.split(x, 4)

In [ ]:
x = np.arange(16).reshape(4, 4)
print(x)
np.split(x, 2)

In [ ]:
x = np.arange(16).reshape(4, 4)
print(x)
np.split(x, 2, axis=1)

## broadcast

In [ ]:
x = np.array([1,2,3])
x + 1

In [ ]:
x = np.arange(1, 10).reshape(3, 3)
y = np.arange(1, 4)
x + y

In [ ]:
x = np.array([10, 20, 30]).reshape(3, 1)
y = np.arange(1, 4)
x + y

## 연산 및 집계함수

In [6]:
x = np.arange(3, 7).reshape(2, 2)
y = np.arange(4).reshape(2, 2)
x.dot(y) #행렬곱

array([[ 8, 15],
       [12, 23]])

In [ ]:
np.transpose(x) #전치행렬

In [ ]:
np.linalg.inv(x) #역행렬

In [ ]:
np.linalg.det(x) #행렬식

In [ ]:
np.median(x) #중간값

In [ ]:
np.std(x) #표준편차

In [ ]:
np.var(x) #분산

In [ ]:
np.sum(x) #합

In [ ]:
np.sum(x, axis=1) #합, 축변경

In [ ]:
np.cumsum(x) #누적합

In [ ]:
np.argmin(x) #최소값 위치

In [ ]:
np.argmax(x) #최대값 위치

In [ ]:
np.any(x) #하나라도 참이어야 참

In [ ]:
np.all(x) #모든요소가 참이어야 참

In [ ]:
np.all(x > 4)

In [ ]:
np.where(x > 4)

In [ ]:
np.where(x > 4, x, -100)

## 실습1

x=[1, 2, 3, 4, 5, 6, 7, 8, 9], y=[10, 20, 30, 40, 50, 60, 70, 80, 90]
위의 배열로 Numpy를 사용하여 3 X 3 행렬을 만든 뒤 행렬합과 행렬곱을 구해주세요.
결과:
[[11 22 33]
[44 55 66]
[77 88 99]]
[[300 360 420]
[660 810 960]
[1020 1260 1500]

In [1]:
import numpy as np

In [20]:
x=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)
y=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90]).reshape(3,3)

z1=np.array([x+y])
print(z1)

z2=np.dot(x,y)
print(z2)

[[[11 22 33]
  [44 55 66]
  [77 88 99]]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


## 실습2

1에서 20사이의 균일한간격으로 30개의 숫자를 만들고
모든값에 숫자10을 더해주세요
결과:
[11. 11.65517241 12.31034483 12.96551724 13.62068966 14.27586207
14.93103448 15.5862069 16.24137931 16.89655172 17.55172414 18.20689655
18.86206897 19.51724138 20.17241379 20.82758621 21.48275862 22.13793103
22.79310345 23.44827586 24.10344828 24.75862069 25.4137931 26.06896552
26.72413793 27.37931034 28.03448276 28.68965517 29.34482759 30. ]


In [24]:
x=np.linspace(1,20,30,endpoint=True)
print(x+10)

[11.         11.65517241 12.31034483 12.96551724 13.62068966 14.27586207
 14.93103448 15.5862069  16.24137931 16.89655172 17.55172414 18.20689655
 18.86206897 19.51724138 20.17241379 20.82758621 21.48275862 22.13793103
 22.79310345 23.44827586 24.10344828 24.75862069 25.4137931  26.06896552
 26.72413793 27.37931034 28.03448276 28.68965517 29.34482759 30.        ]


## 실습3

1~100까지 난수가 들어가있는 2x10x10 배열을 만들고
50보다 크거나 같은 값은 1, 50보다 작은 값은 2로 변환하고
2번째 배열에 아래와 같이 붉은색 위치만 뽑아주세요

In [44]:
x=np.random.randint(1,100,size=(2,10,10))

print(x)
y=np.where(x>=50,1,2)
print(y)

print(y[1,5:,5:])


[[[41  6 81 39 85 71 87  1 70 60]
  [69  9 32 32 89  8 87 92 93 25]
  [68  3 46 34 47 84 94 65 33 17]
  [82 52 59 13 69 65 64 10 51 51]
  [90  9 35 19 50 84 47 67  8  3]
  [60 79 85 82 49 85 91 50 95 50]
  [66 74 91 27 83 36 96 26 54 49]
  [ 7 43 12 40 32 41 64 64  5  4]
  [39 89 14 73 91 76 42 61 74 73]
  [59 93 29 92 62 55 89 51 75 94]]

 [[77 81 71 53 26 90 30 21 16 44]
  [54 26 62 26 31 16 59 60 91 99]
  [35  3 55 71 81 33 71 39 29  1]
  [95 83  6 54 14 46 31 64 17 21]
  [35 51 15 13  8 41 36 64 70 58]
  [63 36 84 54 95 69 81 26  3 59]
  [51 32 13  3 75 32 67 98 43 48]
  [33 51 36  5 45 79 50 81 22  3]
  [91 40 78 57 36 39 21 76 56 57]
  [48 72 20 63 59  5 16  6  1 94]]]
[[[2 2 1 2 1 1 1 2 1 1]
  [1 2 2 2 1 2 1 1 1 2]
  [1 2 2 2 2 1 1 1 2 2]
  [1 1 1 2 1 1 1 2 1 1]
  [1 2 2 2 1 1 2 1 2 2]
  [1 1 1 1 2 1 1 1 1 1]
  [1 1 1 2 1 2 1 2 1 2]
  [2 2 2 2 2 2 1 1 2 2]
  [2 1 2 1 1 1 2 1 1 1]
  [1 1 2 1 1 1 1 1 1 1]]

 [[1 1 1 1 2 1 2 2 2 2]
  [1 2 1 2 2 2 1 1 1 1]
  [2 2 1 1 1 2 1 2 2 2]
  