In [4]:
# 행렬 합 구하기

matrix_1 = [
    [1,2],
    [3,4]
]

matrix_2 = [
    [5,6],
    [7,8]
]
# 에상결과
# result= [
#   [6,8],
#   [10,12]
# ]

In [5]:
result = [
    [0, 0],
    [0, 0]
]

for row in range(2):
    for column in range(2):
        result[row][column] = matrix_1[row][column] + matrix_2[row][column]

In [7]:
result

[[6, 8], [10, 12]]

In [6]:
# 각 요소에 1씩 더하기
matrix_1

for row in range(2):
    for column in range(2):
        matrix_1[row][column] += 1
print(matrix_1)

[[2, 3], [4, 5]]


In [7]:
import numpy as np

In [8]:
# 행렬 합 구하기 with numpy

matrix_1 = [
    [1,2],
    [3,4]
]

matrix_2 = [
    [5,6],
    [7,8]
]


In [10]:
matrix_result = np.array(matrix_1) + np.array(matrix_2)

In [11]:
matrix_result

array([[ 6,  8],
       [10, 12]])

In [13]:
x = np.uint(32)

print(x.dtype)

uint32


In [15]:
x = np.array([1,2,3,4])
print(x.dtype)

int32


In [17]:
x = np.float32( [1,2,3,4])

print(x.dtype)

float32


In [18]:
x

array([1., 2., 3., 4.], dtype=float32)

In [20]:
x = np.array( [1,2,3,4],dtype=np.float32)

print(x.dtype)

float32


In [21]:
y = np.int32(x)
print(y.dtype)

int32


In [23]:
x = np.array(1)
print(x.shape)
print(x.ndim)
print(x.size)

()
0
1


In [26]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)
print(x.ndim)
print(x.size)

(2, 3)
2
6


In [27]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
x= np.arange(10.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
x = np.arange(1,10,0.5)
print(x.dtype)
x

float64


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [33]:
x= np.arange(10, 1, -0.5)
x

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5])

In [34]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [35]:
np.linspace(1,20,5, endpoint=False)

array([ 1. ,  4.8,  8.6, 12.4, 16.2])

In [37]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [42]:
x = np.array([[1,2],[3,4],[5,6]])
print(x.shape)
x.reshape(2,3)

(3, 2)


array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
x = np.arange(20)
print(x)
print(x[1:3])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2]


In [46]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
x[0:3,3:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])

In [49]:
x = np.arange(30).reshape(2,5,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [50]:
x[:,3:,:2]

array([[[ 9, 10],
        [12, 13]],

       [[24, 25],
        [27, 28]]])

In [51]:
x=np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
x[2][2]

12

In [53]:
print(x[[2,2],[3,1]])

[13 11]


In [54]:
x[x>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
x[x==1]

array([1])

In [56]:
(x>3) & (x<8)

array([[False, False, False, False,  True],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [57]:
np.random.rand(5,5)

array([[0.87944323, 0.13167437, 0.23430201, 0.42604413, 0.71531404],
       [0.13249089, 0.02202727, 0.27440475, 0.06931669, 0.15953895],
       [0.52206991, 0.27664074, 0.57738635, 0.72826319, 0.63159868],
       [0.03690672, 0.033045  , 0.02454909, 0.45294959, 0.17154962],
       [0.07540197, 0.65199852, 0.77592733, 0.36844103, 0.11085372]])

In [58]:
x= np.array([10,20,30]).reshape(3,1)
x

array([[10],
       [20],
       [30]])

In [59]:
y=np.arange(1,4)
y

array([1, 2, 3])

In [60]:
x+y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])